name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-13

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app

    - name: Resolve dependencies (if using SwiftPM)
      run: swift package resolve

    - name: Build project
      run: xcodebuild -scheme infitinyCI -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' clean build

    - name: Run tests
      run: xcodebuild test -scheme infitinyCI -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4'
